/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.h
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its H file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#ifndef _SC_INIT_H_
#define _SC_INIT_H_

#include "sc32_conf.h"

void SC_Init(void);
void SC_NVIC_Init(void);
void SC_SYSTICK_Init(void);
void SC_RCC_Init(void);
void SC_OPTION_Init(void);
void SC_GPIO_Init(void);

void SC_UART0_Init(void);
void SC_UART1_Init(void);
void SC_UART2_Init(void);
void SC_UART3_Init(void);
void SC_UART4_Init(void);
void SC_UART5_Init(void);

void SC_TIM0_Init(void);
void SC_TIM1_Init(void);
void SC_TIM2_Init(void);
void SC_TIM3_Init(void);
void SC_TIM4_Init(void);
void SC_TIM5_Init(void);
void SC_TIM6_Init(void);
void SC_TIM7_Init(void);

void SC_PWM0_Init(void);

void SC_LEDPWM_Init(void);

void SC_INT_Init(void);
void SC_ADC_Init(void);
void SC_IAP_Init(void);

void SC_VREF_Init(void);
void SC_DAC_Init(void);
void SC_TemperSensor_Init(void);

void SC_PCAP_Init(void);
void SC_EPWM_Init(void);

void SC_OP_Init(void);

void SC_OP0_Init(void);
void SC_OP1_Init(void);
void SC_OP2_Init(void);

void SC_CAN_Init(void);

void SC_QEP0_Init(void);
void SC_QEP1_Init(void);

void SC_TWI0_Init(void);
void SC_TWI1_Init(void);
void SC_TWI2_Init(void);
void SC_TWI3_Init(void);


void SC_SPI0_Init(void);
void SC_SPI1_Init(void);
void SC_SPI2_Init(void);
void SC_SPI3_Init(void);


void SC_QSPI0_Init(void);
void SC_QSPI1_Init(void);


void SC_BTM_Init(void);
void SC_CRC_Init(void);

void SC_DMA0_Init(void);
void SC_DMA1_Init(void);

void SC_DMA2_Init(void);
void SC_DMA3_Init(void);

void SC_WDT_Init(void);
void SC_PWR_Init(void);

void SC_LCD_Init(void);
void SC_LED_Init(void);

void SC_MR_Init(void);

void SC_ACMP_Init(void);

void SC_ACMP0_Init(void);
void SC_ACMP1_Init(void);
void SC_ACMP2_Init(void);
void SC_ACMP3_Init(void);


#endif

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/
