/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"



/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_TIM0_Init();
	SC_TIM7_Init();
	SC_LED_Init();
	SC_UART2_Init();
	SC_UART5_Init();
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(ENABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_HIRCDIV1Cmd(DISABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC_2);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB2Config(RCC_HCLK_Div1);
	RCC_APB2Cmd(ENABLE);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
	RCC_APB1Config(RCC_HCLK_Div1);
	RCC_APB1Cmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(160000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PA00 Struct*/GPIO_InitTypeDef GPIOInit_PA00_Struct;
	GPIOInit_PA00_Struct.GPIO_Pin = GPIO_Pin_0;
	GPIOInit_PA00_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA00_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA00_Struct);/*RxD2�˿ڳ�ʼ��*/
	/*GPIOInit_PA01 Struct*/GPIO_InitTypeDef GPIOInit_PA01_Struct;
	GPIOInit_PA01_Struct.GPIO_Pin = GPIO_Pin_1;
	GPIOInit_PA01_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA01_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA01_Struct);/*TxD2�˿ڳ�ʼ��*/
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_UART2, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 32000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART2, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART2,UART_IT_EN,ENABLE);
	/*INT_TX*/UART_ITConfig(UART2,UART_IT_TX,DISABLE);
	/*INT_RX*/UART_ITConfig(UART2,UART_IT_RX,ENABLE);
	/*INT_BK*/UART_ITConfig(UART2,UART_IT_BK,DISABLE);
	/*INT_SL*/UART_ITConfig(UART2,UART_IT_SL,DISABLE);
	/*INT_SY*/UART_ITConfig(UART2,UART_IT_SY,DISABLE);
	/*Init Struct*/NVIC_SetPriority(UART0_2_4_IRQn,2);/*UART0_2_4*/
	NVIC_EnableIRQ(UART0_2_4_IRQn);
	/*Init Struct*/UART_PinRemapConfig(UART2,UART_PinRemap_Default);
	UART_TXCmd(UART2,ENABLE);
	UART_RXCmd(UART2,ENABLE);
	Printf_UartInit(UART2);
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PC00 Struct*/GPIO_InitTypeDef GPIOInit_PC00_Struct;
	GPIOInit_PC00_Struct.GPIO_Pin = GPIO_Pin_0;
	GPIOInit_PC00_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC00_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC00_Struct);/*TxD5¶˿ڳõʼ»¯*/
	/*GPIOInit_PC01 Struct*/GPIO_InitTypeDef GPIOInit_PC01_Struct;
	GPIOInit_PC01_Struct.GPIO_Pin = GPIO_Pin_1;
	GPIOInit_PC01_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC01_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC01_Struct);/*RxD5¶˿ڳõʼ»¯*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_UART5, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 32000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART5, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART5,UART_IT_EN,ENABLE);
	/*INT_TX*/UART_ITConfig(UART5,UART_IT_TX,DISABLE);
	/*INT_RX*/UART_ITConfig(UART5,UART_IT_RX,ENABLE);
	/*Init Struct*/NVIC_SetPriority(UART1_3_5_IRQn,3);/*UART1_3_5*/
	NVIC_EnableIRQ(UART1_3_5_IRQn);
//	/*INT_EN*/UART_ITConfig(UART5,UART_IT_EN,DISABLE);
	/*Init Struct*/UART_PinRemapConfig(UART5,UART_PinRemap_Default);
	UART_TXCmd(UART5,ENABLE);
	UART_RXCmd(UART5,ENABLE);
	//Printf_UartInit(UART5);
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TIM0,ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_1;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 33536;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM0, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM0, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM0, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM0, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM0, TIM_PWMChannel_PWMA,50);
	/*PWMB Duty*/TIM_PWMSetDuty(TIM0, TIM_PWMChannel_PWMB,50);
	/*INTEN*/TIM_ITConfig(TIM0,TIM_IT_INTEN, ENABLE);
	/*TI*/TIM_ITConfig(TIM0,TIM_IT_TI, ENABLE);
	/*Init Struct*/NVIC_SetPriority(TIMER0_IRQn,3);/*TIMER0*/
	NVIC_EnableIRQ(TIMER0_IRQn);
	TIM_Cmd(TIM0,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM7, ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_1;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 33536;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM7, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM7, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM7, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM7, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM7, TIM_PWMChannel_PWMA,50);
	/*PWMB Duty*/TIM_PWMSetDuty(TIM7, TIM_PWMChannel_PWMB,50);
	/*INTEN*/TIM_ITConfig(TIM7,TIM_IT_INTEN, ENABLE);
	/*TI*/TIM_ITConfig(TIM7,TIM_IT_TI,ENABLE);
	/*Init Struct*/NVIC_SetPriority(TIMER6_7_IRQn,3);/*TIMER6_7*/
	NVIC_EnableIRQ(TIMER6_7_IRQn);
	TIM_Cmd(TIM7,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*Init Struct*/ADC_InitTypeDef ADC_Base_InitStruct;
	ADC_Base_InitStruct.ADC_ConvMode = ADC_ConvMode_Single;
	ADC_Base_InitStruct.ADC_Prescaler = ADC_Prescaler_3CLOCK;
	ADC_Base_InitStruct.ADC_EAIN = ADC_EAIN_Less|ADC_EAIN_15;
	ADC_Base_InitStruct.ADC_VREF = ADC_VREF_VDD;
	ADC_Init(ADC, &ADC_Base_InitStruct);
	ADC_SetChannel(ADC,ADC_Channel_OP);
	/*ADCIF*/ADC_ITConfig(ADC,ADC_IT_ADCIF, ENABLE);
	ADC_DMACmd(ADC,DISABLE);
	/*Init Struct*/NVIC_SetPriority(ADC_IRQn,1);/*ADC*/
	NVIC_EnableIRQ(ADC_IRQn);
	ADC_Cmd(ADC,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief VREF init
  * @note 
  * @param
  */
void SC_VREF_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DAC init
  * @note 
  * @param
  */
void SC_DAC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TemperSensor init
  * @note 
  * @param
  */
void SC_TemperSensor_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief PCAP init
  * @note 
  * @param
  */
void SC_PCAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief EPWM init
  * @note 
  * @param
  */
void SC_EPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}





/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PA03 Struct*/GPIO_InitTypeDef GPIOInit_PA03_Struct;
	GPIOInit_PA03_Struct.GPIO_Pin = GPIO_Pin_3;
	GPIOInit_PA03_Struct.GPIO_Mode = GPIO_Mode_IN_HI;
	GPIOInit_PA03_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA03_Struct);/*OP_P0�˿ڳ�ʼ��*/
	/*GPIOInit_PA04 Struct*/GPIO_InitTypeDef GPIOInit_PA04_Struct;
	GPIOInit_PA04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PA04_Struct.GPIO_Mode = GPIO_Mode_IN_HI;
	GPIOInit_PA04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA04_Struct);/*OP_N�˿ڳ�ʼ��*/
	/*GPIOInit_PA05 Struct*/GPIO_InitTypeDef GPIOInit_PA05_Struct;
	GPIOInit_PA05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PA05_Struct.GPIO_Mode = GPIO_Mode_IN_HI;
	GPIOInit_PA05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA05_Struct);/*OP_O�˿ڳ�ʼ��*/
	/*Init Struct*/OP_InitTypeDef OP_InitStruct;
	OP_InitStruct.OP_ShortCircuit = OP_ShortCircuit_OFF;
	OP_InitStruct.OP_FDBResisrance = OP_FDBResisrance_VSS;
	OP_InitStruct.OP_PGAGain = OP_PGAGain_NonInvert8_Invert7;
	OP_InitStruct.OP_Posittive = OP_Posittive_OPP0;
	OP_InitStruct.OP_Negative = OP_Negative_OPN;
	OP_InitStruct.OP_Output = OP_Output_ON;
	OP_Init(OP, &OP_InitStruct);
	OP_Cmd(OP,ENABLE);
	OP_OffsetSet(OP);
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief OP0 init
  * @note 
  * @param
  */
void SC_OP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}
/**
  * @brief OP1 init
  * @note 
  * @param
  */
void SC_OP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief OP2 init
  * @note 
  * @param
  */
void SC_OP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief QEP0 init
  * @note 
  * @param
  */
void SC_QEP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief QEP1 init
  * @note 
  * @param
  */
void SC_QEP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}




/**
  * @brief CAN init
  * @note 
  * @param
  */
void SC_CAN_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI3 init
  * @note
  * @param
  */
void SC_SPI3_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI2 init
  * @note
  * @param
  */
void SC_TWI2_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TWI3 init
  * @note
  * @param
  */
void SC_TWI3_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief LCD init
  * @note 
  * @param
  */

void SC_LCD_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC LED Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_LCDLEDCLKSource_TypeDef RCC_LCDLEDCLKSource = RCC_LCDLEDCLKSource_LIRC;
	RCC_LCDLEDCLKConfig(RCC_LCDLEDCLKSource);
	/*Init Struct*/RCC_APB2PeriphClockCmd(RCC_APB2Periph_LCD_LED, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_LEDPWM, ENABLE);
	/*Init Struct*/LED_InitTypeDef LED_InitStruct;
	LED_InitStruct.LED_FrameFre = LED_FrameFre_A128Hz;
	LED_InitStruct.LED_Duty = LED_Duty_1_4_SEG0_27COM4_7;
	LED_InitStruct.LED_ComPin = 0x0000 | LED_COMEN_4| LED_COMEN_5| LED_COMEN_6| LED_COMEN_7;
	LED_InitStruct.LED_SegPin = 0x0000 | LED_Channel_8| LED_Channel_9| LED_Channel_10| LED_Channel_11| LED_Channel_12| LED_Channel_13| LED_Channel_14| LED_Channel_15;
	LED_Init(&LED_InitStruct);
	LED_Cmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief SC MR Init
  * @note 
  * @param
  */
void SC_MR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP Init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP0 Init
  * @note 
  * @param
  */
void SC_ACMP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP1 Init
  * @note 
  * @param
  */
void SC_ACMP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP2 Init
  * @note 
  * @param
  */
void SC_ACMP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP3 Init
  * @note 
  * @param
  */
void SC_ACMP3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC QSPI0 Init
  * @note
  * @param
  */
void SC_QSPI0_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief SC QSPI1 Init
  * @note
  * @param
  */
void SC_QSPI1_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
