/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_it.h
  * @author	 
  * @version 	
  * @date	
  * @brief	         Interrupt service program header file
  * @details         
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#ifndef _SC_IT_H_
#define	_SC_IT_H_

#include "sc32_conf.h"




void INT0_IRQHandler(void);
void INT1_7_IRQHandler(void);
void INT8_11_IRQHandler(void);
void INT12_15_IRQHandler(void);
void RCC_IRQHandler(void);

#if !defined (TK_USE_BTM)
void BTM_IRQHandler(void);
#endif

void UART1_IRQHandler(void);
void UART1_3_IRQHandler(void);
void UART1_3_5_IRQHandler(void);
	
void UART0_2_IRQHandler(void);
void UART0_2_4_IRQHandler(void);

void SPI0_IRQHandler(void);
void SPI1_IRQHandler(void);
void SPI1_2_IRQHandler(void);

void DMA0_IRQHandler(void);
void DMA1_IRQHandler(void);

void DMA2_IRQHandler(void);
void DMA3_IRQHandler(void);

void TIMER0_IRQHandler(void);
void TIMER1_IRQHandler(void);
void TIMER2_IRQHandler(void);
void TIMER3_IRQHandler(void);

void TIMER4_5_IRQHandler(void);
void TIMER6_7_IRQHandler(void);

void PCAP_IRQHandler(void);
void EPWM_IRQHandler(void);

void QEP0_IRQHandler(void);
void QEP1_IRQHandler(void);
void OP1_OP2_IRQHandler(void);
void SPI1_TWI1_IRQHandler(void);

void CAN_IRQHandler(void);

void PWM0_IRQHandler(void);

void LEDPWM_IRQHandler(void);

void TWI0_IRQHandler(void);

void TWI1_IRQHandler(void);

void ADC_IRQHandler(void);

void CMP0_1_2_IRQHandler(void);
void CMP3_IRQHandler(void);
void CMP_IRQHandler(void);

void SysTick_IRQHandler(void);
void TWIx_QSPIx_1_3_IRQHandler(void);
void TWIx_QSPIx_0_2_IRQHandler(void);


#endif


/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/
